version: '3'

services:
  serverless:
    container_name: sls-environment
    build:
      context: ./docker/serverless
    volumes:
      - ./:/home/serverless
    ports:
      - "3000:3000"
    depends_on:
      - database
    
  database:
    container_name: sls-database
    image: arm64v8/mysql:oracle
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-database