name: AWS Service Deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage to deploy (prd/dev)'     
        required: true

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:gallium-alpine
    
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Install serverless
       run: npm i -g serverless

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: sa-east-1

     - name: Create environment file
       run: 'touch env/env.${{ github.event.inputs.stage }}.yml'

     - name: Add database configuration to environment
       run: 'echo ${{ github.event.inputs.stage }}_database_config >> env/env.${{ github.event.inputs.stage }}.yml'
       env:
        prd_database_config: ${{secrets.PROD_DATABASE_CONFIGURATION}}
        dev_database_config: ${{secrets.DEV_DATABASE_CONFIGURATION}}
       
     - name: Install dependencies
       run: yarn

     - name: Run deploy
       run:  sls deploy -s ${{ github.event.inputs.ambiente }}